size(500,500);
int m =5;
int mijneerstevariable =5;
mijneerstevariable =5;
println(mijneerstevariable);mijneerstevariable =15;
println(mijneerstevariable);
int a = 2;
int b = 10;
int totaal = 0;
totaal = a + b;
println(totaal);
totaal =  a * b;
println(totaal);
totaal = a - b;
println(totaal);
totaal = 5+10;
println(totaal);
totaal  = 6*4;
println(totaal);
totaal = 24-2;
println(totaal);
